"""add_plant_icon_column

Revision ID: 0a8e4d7ed3d1
Revises: 17856973d7f9
Create Date: 2025-10-04 15:35:36.934243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a8e4d7ed3d1'
down_revision: Union[str, None] = '17856973d7f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('plant_icon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'plant_icon')
    # ### end Alembic commands ###
