"""ensure_plant_id_nullable_constraint

Revision ID: 77f2e5558035
Revises: a33d08e24a60
Create Date: 2025-10-04 22:39:45.298111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77f2e5558035'
down_revision: Union[str, None] = 'a33d08e24a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
