"""make_plant_id_nullable_in_plant_scans

Revision ID: a33d08e24a60
Revises: d0acb61cdf34
Create Date: 2025-10-04 22:34:11.358541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33d08e24a60'
down_revision: Union[str, None] = 'd0acb61cdf34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plant_scans', 'plant_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('plants', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('plant_scans', 'plant_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
