"""remove_care_notes_from_plants

Revision ID: d0acb61cdf34
Revises: cb5efb5f6219
Create Date: 2025-10-04 21:57:15.130790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0acb61cdf34'
down_revision: Union[str, None] = 'cb5efb5f6219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'care_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('care_notes', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
